variables:
#  SSH_CONNECTION: 'nojaf@'
  IMAGE_NAME: registry.gitlab.servers.mollux.be/nojaf/redhood:$CI_COMMIT_REF_NAME
  MASTER_PORT: 9700

stages:
  - build
  - create
#  - deploy

build code:
  stage: build
  image: microsoft/dotnet:2.2-sdk
  script:
    - dotnet tool install --tool-path ".paket" Paket --add-source https://api.nuget.org/v3/index.json
    - dotnet tool install fake-cli --tool-path .fake
    - .fake/fake run build.fsx -t Pack
  tags:
    - docker
  artifacts:
    name: "${CI_PROJECT_PATH}__${CI_BUILD_REF_NAME}"
    paths:
      - ./artifacts
    expire_in: 1h
  only:
    - master

create container:
  stage: create
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.servers.mollux.be/
    - docker build -t ${IMAGE_NAME} .
    - docker push ${IMAGE_NAME}
  only:
    - master
  tags:
    - shell
  dependencies:
    - build code

#deploy container master:
#  stage: deploy
#  script:
#    - ssh ${SSH_CONNECTION} "sudo /var/www/vhosts/teams.budapestrally.org/reload_rds.sh $CI_COMMIT_REF_NAME $MASTER_PORT"
#  only:
#    - master
#  tags:
#    - shell
#  dependencies:
#    - create container
