language: minimal

services:
  - docker

sudo: required

before_install:
  - docker pull nojaf/fable:2.3

jobs:
  include:
    - stage: "CI"
      script: docker run --network=host -v "${PWD}:/app" -w "/app" nojaf/fable:2.3 bash -c "fake run build.fsx"
