version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
    - master
install:
  # Install repo specific stuff here
  - cmd: dotnet tool install --tool-path ".paket" Paket --add-source https://api.nuget.org/v3/index.json
  - cmd: dotnet tool install fake-cli --tool-path .fake
build_script:
  - cmd: ls .fake
  - cmd: .fake/fake.exe run build.fsx -t Tests